image: node:lts-buster

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  rules: &rules
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE =~ /^chore\(release\)/'

ftp:
  stage: deploy
  dependencies:
    - build
  script:
    - apt-get update -qy
    - apt-get install -y lftp
    - lftp ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_HOST -e "set ftp:ssl-allow no; mirror --reverse --delete --exclude .ftpquota --exclude .htaccess --ignore-time --verbose public/ /; exit;"
  rules: *rules

# pages:
#   script:
#     - npm install
#     - npm run build
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE =~ /^chore\(release\)/' 
